version: '3'
services:
  zhiya-api:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["api"]
    expose:
      - 8079
    ports:
      - 8079:8079 
  zhiya-mqueue:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["mqueue"]
  zhiya-queue-uchat.chat.create:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.chat.create"]
  zhiya-queue-uchat.chat.keyword:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.chat.keyword"]
  zhiya-queue-uchat.chat.message:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.chat.message"]
  zhiya-queue-uchat.member.join:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.member.join"]
  zhiya-queue-uchat.member.list:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.member.list"]
  zhiya-queue-uchat.member.message_sum:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.member.message_sum"]
  zhiya-queue-uchat.member.quit:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.member.quit"]
  zhiya-queue-uchat.mysql.message.queue:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.mysql.message.queue"]
  zhiya-queue-uchat.robot.chat.list:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.robot.chat.list"]
  zhiya-queue-uchat.chat.qrcode:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.chat.qrcode"]
  zhiya-queue-uchat.robot.friend.add:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.robot.friend.add"]
  zhiya-queue-uchat.robot.chat.join:
    image: edwinlll/zhiya:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - ./.zhiya.yaml:/usr/local/zhiya/.zhiya.yaml
    command: ["uchat", "--queue", "uchat.robot.chat.join"]
